### ISSUE TITLE
Too relaxed value validator?

### ISSUE THREAD

**Issue by megapctr** [visionmedia/bytes.js#31]
I just noticed this behavior:
```js
> bytes('250Kg');
250
> bytes('250 e-mails');
250
```

Is this a bug? I would expect a `NaN` instead of `250B`, like in this example:
```js
> bytes('something 250');
NaN
```

**Comment by dougwilson** [comment]
Hi @megapctr, thanks for the report! It does look like an oversight in the parsing. I would actually go as far as say I would except both of those examples to throw an error, rather than simply return `NaN`, since the purpose is to parse, and that would be a parse error. Otherwise, returning `null` would be in line with the other inputs you can give.

@theofidry do you have any thoughts on this?

**Comment by theofidry** [comment]
Will look into it tonight :)

**Comment by theofidry** [comment]
Will look into it :)

**Comment by megapctr** [comment]
Thanks for super quick reaction to my issue! :zap:
I see that bytes@2.3.0 doesn't include this fix, what's the eta for 2.4.0?

**Comment by theofidry** [comment]
@megapctr we cannot ship it for 2.x as it brings breaking changes (you can no longer use `bytes('2 bytes')` for example. So it will be for the next major release.

@dougwilson do you have any release date in mind?

**Comment by dougwilson** [comment]
@theofidry release for 3.0 is just as soon as we feel it's ready to go :) I did find a couple things I wanted to fix, and should make issues here in this repo to tack (and for anyone else to make a PR for before I can).

**Comment by theofidry** [comment]
:+1:
